#!/usr/bin/env bash


config() {
  # host list
  host_list="${1:-$HOME/.holi}"
  # default host list
  if [ ! -f "$host_list" ]; then
    touch $HOME/.holi
  fi
  #  print_green "use host list file:$host_list"
}


#font color
reset_color="\033[0m"

print_green(){
  echo -e "\033[32m"${1}${reset_color}
}

print_red(){
  echo -e "\033[31m"${1}${reset_color}
}

print_title(){
  echo -e "\033[42;1mID\tIP\t\t\tUSER\t\t\t\033[0m";
}

holi(){
while (true);do
  id=1
  numbers=""
  for hostname in `grep -Ev "^$|[#;]" $host_list`
    do
      user=${hostname%%@*}
      ip=${hostname##*@}
      #check ip
      echo $ip|grep "^[0-9]\{1,3\}\.\([0-9]\{1,3\}\.\)\{2\}[0-9]\{1,3\}$" > /dev/null;
    if [ $? -ne 0 ];then
      echo error ip address about $user@$ip
      exit 1
    fi
      echo -e "${id}\t${ip}\t\t${user}\t\t\t"
      hosts[${id}]=${hostname}
      numbers="${numbers}|${id}"
      id=$((id+1))
    done
	numbers="("${numbers}")"
	print_green "select host ID:"
	read userinput 
	for index in ${!hosts[@]};do
	  if [ "$userinput" == $index ];then
	    ssh ${hosts[$userinput]}
	    break
	  fi
	done
        print_red "press [Exit/E/e] to exit"
        case $userinput in
            [Ee][Xx][Ii][Tt]|[Ee]) exit 0;;
        esac
	print_title
done
}

main(){
config $1
print_title
holi
}

main
