apiVersion: v1
data:
  elasticsearch.yml: |
    cluster.name: "docker-cluster"
    network.host: 0.0.0.0

    discovery.zen.minimum_master_nodes: 1

    discovery.type: single-node
    indices.query.bool.max_clause_count: 10240


    http.cors.enabled: true
    http.cors.allow-origin: "*"
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
