ARG ELK_VERSION

# https://github.com/elastic/kibana-docker
FROM harbor.yonyouccs.com/elk6/kibana-oss:${ELK_VERSION}

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
