apiVersion: v1
data:
  elasticsearch.yml: |
    cluster.name: "docker-cluster"
    network.host: 0.0.0.0

    discovery.zen.minimum_master_nodes: 1

    discovery.type: single-node

    xpack.security.enabled: false
    xpack.monitoring.enabled: false
    xpack.ml.enabled: false
    xpack.graph.enabled: false
    xpack.watcher.enabled: false

    http.cors.enabled: true
    http.cors.allow-origin: "*"
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
