# Default values for fastdfs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: harbor.yonyouccs.com/base/webpush
  tag: v1.1.0
  pullPolicy: IfNotPresent
  pullSecrets:
    - regcred

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /eventbus
  hosts:
    - pre.yonyouccs.com
  tls:
  - hosts:
    - pre.yonyouccs.com
    secretName: tls-yonyouccs

env:
  PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/jvm/java-1.8-openjdk/jre/bin:/usr/lib/jvm/java-1.8-openjdk/bin
  JAVA_ALPINE_VERSION: 8.131.11-r2
  JAVA_HOME: /usr/lib/jvm/java-1.8-openjdk
  JAVA_VERSION: 8u131
  jdbc_url: 10.169.2.170:3306
  LANG: C.UTF-8

  jdbc_url: 10.169.2.170:3306
  jdbc_user: ccpreuser
  jdbc_password: tHnpS329YoKI
  redis_host: 10.247.27.188
  redis_port: 6379
  redis_auth: wvPjiSHOIpuF

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  enabled: false
  ## If defined, volume.beta.kubernetes.io/storage-class: <storageClass>
  ## Default: volume.alpha.kubernetes.io/storage-class: default
  ##
  storageClass: alicloud-disk-efficiency
  accessMode: ReadWriteOnce
  size: 10Gi

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 512Mi
    cpu: 300m


nodeSelector: {}

tolerations: []

affinity: {}
