apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness-readiness
  name: liveness-readiness
spec:
  containers:
  - name: liveness-readiness
    image: nginx:alpine
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 3
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 3
