apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: pod-demo-nginx
  namespace: default
spec:
  containers:
  - image: nginx:alpine
    name: nginx
    ports:
    - name: http
      containerPort: 80
