apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-service
  name: nginx-service
  namespace: default
spec:
  clusterIP: 10.97.97.97
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30800
  selector:
    app: nginx
  type: NodePort
