apiVersion: v1
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline

    xpack.monitoring.enabled: false

kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
