apiVersion: v1
data:
  logstash.conf: |
    input {
            tcp {
                    port => {{ .Values.logstash.port }}
                    codec => json_lines
            }
    }

    output {
            elasticsearch {
                    hosts => "{{ .Values.elasticsearch.ip }}:9200"
           }
    }
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-pipeline
