ARG ELK_VERSION

# https://github.com/elastic/elasticsearch-docker
FROM harbor.yonyouccs.com/elk6/elasticsearch-oss:${ELK_VERSION}

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
