{{- if .Release.IsInstall -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "solr.fullname" . }}
  labels:
    app: {{ include "solr.name" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  selector:
    matchLabels:
      app: {{ include "solr.name" . | quote }}
      release: {{ .Release.Name | quote }}
  {{- if .Values.minAvailable }}
  minAvailable: {{ .Values.minAvailable }}
  {{- else }}
  minAvailable: {{ sub .Values.servers 1 }}
  {{- end }}
{{- end -}}
