# Default values for solr.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
image: 
  registry: "harbor.yonyouccs.com/base/solr:c7.3.1"
  pullPolicy: "IfNotPresent"
  pullSecrets:
    - regcred
#command: "[\"solr\"]"
#args: "[\"-f\", \"-c\", \"-m\", \"2g\", \"-z\", \"zookeeper-zookeeper:2181\"]"
replicas: 1
minAvailable: 1
containerPort: 8983
resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: 1
    memory: "4Gi"
heap: "2G"

# only huawei cloud need provider、region、zone
# storageClass: alicloud-disk-efficiency
storageClass: sas

provider: huaweicloud
region: cn-north-1
zone: cn-north-1c 
storage: "50Gi"

tickTimeMs: 2000
initTicks: 10
syncTicks: 5
clientCnxns: 60
snapRetain: 3
purgeHours: 1
probeInitialDelaySeconds: 15
probeTimeoutSeconds: 5
antiAffinity: "hard"
logLevel: "INFO"
security:
  enabled: true
  runAsUser: 8983
  fsGroup: 8983
