## openjdk image version
##
image:
  registry: harbor.17elian.com
  repository: elian/ejc-eureka
  tag: 3.0.0-SNAPSHOT-03271636

  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  pullPolicy: IfNotPresent
  pullSecrets:
    - harbor-17elian 

strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
  type: RollingUpdate

env:
  java_opts: "-Xms2048M -Xmx2048M"

service:
  name: http
  type: ClusterIP
  externalPort: 80
  internalPort: 8080 
#serviceType: ClusterIP

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  enabled: false
  ## If defined, volume.beta.kubernetes.io/storage-class: <storageClass>
  ## Default: volume.alpha.kubernetes.io/storage-class: default
  ##
  # storageClass:
  accessMode: ReadWriteOnce
  size: 8Gi

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 1024Mi
    cpu: 200m
#  limits:
#    cpu: 500m
#    memory: 2048Mi

ingress:
  enabled: false
  #annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts: dev.17elian.com
  tls:
  - hosts:
    - dev.17elian.com
    secretName: tls-17elian

## healthcheck
readinessProbe:
  path: "/eurekaserver/actuator/health"
  initialDelaySeconds: 60
  periodSeconds: 30
  failureThreshold: 6
  timeoutSeconds: 5
livenessProbe:
  path: "/eurekaserver/actuator/health"
  initialDelaySeconds: 60
  periodSeconds: 30
  failureThreshold: 6
  timeoutSeconds: 5

#healthcheck:
#  path: monitor/PING
